Repository Quaran-Team/client-EarthBnB, pull requests merged in 2020-09, with the labels that each got.

#38 Feature/brian photo starter
  angular.json
  src/app/app.component.html
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/brian-photo/brian-photo.component.css
  src/app/brian-photo/brian-photo.component.html
  src/app/brian-photo/brian-photo.component.spec.ts
  src/app/brian-photo/brian-photo.component.ts
  src/index.html
Labels: chore, enhancement, feature

#50 Feature/pictures
  src/app/app.component.html
  src/app/app.module.ts
  src/app/brian-photo/brian-photo.component.css
  src/app/brian-photo/brian-photo.component.html
Labels: enhancement, feature

#53 Chore/brian testin
  README.md
  src/app/app.component.spec.ts
  src/app/brian-photo/brian-photo.component.html
  src/app/brian-photo/brian-photo.component.spec.ts
Labels: chore, documentation, enhancement, feature

#77 Addition of the location component files
  src/app/app.component.html
  src/app/app.module.ts
  src/app/location/location.component.css
  src/app/location/location.component.html
  src/app/location/location.component.spec.ts
  src/app/location/location.component.ts
Labels: feature, t.x-small

#76 had to go undynamic for some fluke reason
  src/app/brian-photo/brian-photo.component.html
  src/app/brian-photo/brian-photo.component.ts
Labels: bug

#79 Feature/photo data from server
  src/app/app.module.ts
  src/app/brian-photo/brian-photo.component.html
  src/app/brian-photo/brian-photo.component.ts
  src/app/services/photos.service.spec.ts
  src/app/services/photos.service.ts
Labels: enhancement, feature

#85 buttons click through first 4 picture sets working
  src/app/brian-photo/brian-photo.component.html
  src/app/brian-photo/brian-photo.component.ts
  src/app/services/photos.service.ts
Labels: enhancement, feature

#93 Feature/make modal gallery
  src/app/brian-photo/brian-photo.component.css
  src/app/brian-photo/brian-photo.component.html
  src/app/brian-photo/brian-photo.component.ts
  src/app/services/photos.service.ts
Labels: enhancement, feature

#95 Feature/photo gal css
  package-lock.json
  src/app/brian-photo/brian-photo.component.css
  src/app/brian-photo/brian-photo.component.html
  src/app/brian-photo/brian-photo.component.ts
Labels: bug

#97 Feature/reviews
  .gitignore
  src/app/Reviews/reviews.component.css
  src/app/Reviews/reviews.component.html
  src/app/Reviews/reviews.component.spec.ts
  src/app/Reviews/reviews.component.ts
  src/app/app.module.ts
  src/app/directory/directory.component.html
  src/app/services/reviews.service.ts
Labels: feature, t.small

#104 Feature/reviews get route params
  src/app/Reviews/reviews.component.css
  src/app/Reviews/reviews.component.html
  src/app/app-routing/app-routing.module.ts
Labels: enhancement

#105 Feature/reviews get route params
  src/app/Reviews/reviews.component.css
  src/app/Reviews/reviews.component.html
Labels: t.x-small

#108 gallery in right spot looking ok
  src/app/brian-photo/brian-photo.component.css
  src/app/brian-photo/brian-photo.component.html
  src/app/directory/directory.component.html
  src/app/listingInfo/listing-info-container/listing-info-container.component.html
Labels: chore, enhancement, feature

#110 can change with buttons or thru url - some more picky css stuff added…
  src/app/brian-photo/brian-photo.component.css
  src/app/brian-photo/brian-photo.component.html
  src/app/brian-photo/brian-photo.component.ts
Labels: feature

#128 Feature/things to do bwl
  src/app/brian-ttd/brian-ttd.component.css
  src/app/brian-ttd/brian-ttd.component.html
  src/app/brian-ttd/brian-ttd.component.ts
  src/app/directory/directory.component.html
Labels: chore, enhancement, feature
